<template>
  <div class="relative w-full max-w-md h-screen flex flex-col bg-[#121212] overflow-hidden mx-auto">
    <!-- Header Area -->
    <div class="pt-8 px-6 pb-2 flex items-center justify-between">
      <h1 class="text-3xl font-bold tracking-tight text-white">History</h1>
      <button 
        class="text-base-content/40 hover:text-white transition-colors"
        @click="openExportModal"
      >
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
      </button>
    </div>

    <!-- Month Navigation -->
    <div class="flex-shrink-0">
      <MonthHeader 
        :month="currentDate.getMonth()"
        :year="currentDate.getFullYear()"
        @prev="prevMonth"
        @next="nextMonth"
      />
    </div>

    <!-- Scrollable Content Area -->
    <div class="flex-1 overflow-y-auto hide-scrollbar pb-32">
      <!-- Calendar Grid -->
      <div class="py-4">
         <CalendarGrid 
           :month="currentDate.getMonth()"
           :year="currentDate.getFullYear()"
           :entries="entries"
           @select-day="handleDaySelect"
         />
      </div>

      <!-- Selected Day Timeline -->
      <div v-if="selectedDate" class="border-t border-base-content/5 mt-2">
        <div class="px-6 pt-4 pb-1">
          <h3 class="text-sm font-medium text-base-content/60">
            Activity for {{ formatDate(selectedDate) }}
          </h3>
        </div>
        
        <Timeline 
          :entries="selectedDayEntries" 
          @edit-entry="openEditModal"
          @add-entry="openAddModal"
        />
      </div>
    </div>

    <!-- Bottom Nav -->
    <BottomNav @add="openAddModal" />

    <!-- Edit Modal -->
    <AddEntryModal ref="addModal" :selected-date="selectedDate" @save="handleSaveEntry" />

    <!-- Export Modal -->
    <ExportModal 
      :is-open="isExportModalOpen"
      @close="closeExportModal"
      @export="handleExport"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useTimeEntriesStore } from '@/stores/timeEntries'
import { useCSVExport } from '@/composables/useCSVExport'
import type { ExportFilters } from '@/composables/useCSVExport'
import MonthHeader from '@/components/history/MonthHeader.vue'
import CalendarGrid from '@/components/history/CalendarGrid.vue'
import Timeline from '@/components/home/Timeline.vue'
import BottomNav from '@/components/layout/BottomNav.vue'
import AddEntryModal from '@/components/entry/AddEntryModal.vue'
import ExportModal from '@/components/history/ExportModal.vue'

// Logic
const store = useTimeEntriesStore()
const { exportToCSV } = useCSVExport()

const currentDate = ref(new Date())
const selectedDate = ref<string>(new Date().toISOString().split('T')[0] || '')
const addModal = ref<InstanceType<typeof AddEntryModal> | null>(null)
const isExportModalOpen = ref(false)

// Entries from store
const entries = computed(() => store.entries)

const selectedDayEntries = computed(() => {
  return store.getEntriesForDay(selectedDate.value)
})

const prevMonth = () => {
  const newDate = new Date(currentDate.value)
  newDate.setMonth(newDate.getMonth() - 1)
  currentDate.value = newDate
}

const nextMonth = () => {
  const newDate = new Date(currentDate.value)
  newDate.setMonth(newDate.getMonth() + 1)
  currentDate.value = newDate
}

const handleDaySelect = (dateStr: string) => {
  selectedDate.value = dateStr 
}

const openEditModal = (entry: any) => {
  if (entry) {
    addModal.value?.open(entry)
  }
}

const openAddModal = () => {
    // Open for currently selected day
    addModal.value?.open()
}

const handleSaveEntry = async (payload: any) => {
  console.log('[History Page] Saving entry', payload)
  
  const [startHour, startMinute] = payload.startTime.split(':').map(Number)
  const [endHour, endMinute] = payload.endTime.split(':').map(Number)

  const date = new Date(selectedDate.value)
  const startTime = new Date(date)
  startTime.setHours(startHour, startMinute, 0, 0)

  const endTime = new Date(date)
  endTime.setHours(endHour, endMinute, 0, 0)
  
  if (endTime < startTime) {
      endTime.setDate(endTime.getDate() + 1);
  }

  try {
    await store.saveEntryForDay(selectedDate.value, {
      id: payload.id,
      startTime: startTime.getTime(),
      endTime: endTime.getTime(),
      tasks: payload.tasks,
      isOvertime: payload.isWeekend,
      autoGenerated: false,
      modifiedAt: Date.now()
    })
  } catch (err) {
    console.error('Failed to save', err)
  }
}

const formatDate = (dateStr: string) => {
  if (!dateStr) return ''
  const date = new Date(dateStr)
  return date.toLocaleDateString('default', { weekday: 'long', day: 'numeric', month: 'long' })
}

// Export functionality
const openExportModal = () => {
  isExportModalOpen.value = true
}

const closeExportModal = () => {
  isExportModalOpen.value = false
}

const handleExport = (filters: ExportFilters) => {
  exportToCSV(entries.value, filters)
}
</script>

<style scoped>
.hide-scrollbar::-webkit-scrollbar {
  display: none;
}
.hide-scrollbar {
  -ms-overflow-style: none;
  scrollbar-width: none;
}
</style>
