import Dexie from 'dexie';

export interface LegacyTimeEntry {
  id?: string;
  date: string; // ISO date YYYY-MM-DD
  hoursWorked: number;
  tasks: string;
  isWeekend: boolean;
  autoGenerated: boolean;
  modifiedAt: number;
  userId?: string;
}

export class TimeTrackerDB extends Dexie {
  timeEntries!: Dexie.Table<LegacyTimeEntry, number>;

  constructor() {
    super('TimeTrackerDB');
    (this as any).version(1).stores({
      timeEntries: '++id, date, modifiedAt' // Primary key and indexes
    });
  }
}

export const db = new TimeTrackerDB();
