import Dexie, { type Table } from 'dexie';
import dexieCloud from 'dexie-cloud-addon';

export interface TimeEntry {
  id?: string;
  date: string; // ISO date YYYY-MM-DD
  startTime: number; // timestamp
  endTime: number; // timestamp
  tasks: string;
  isOvertime: boolean;
  autoGenerated: boolean;
  modifiedAt: number;
  userId?: string; // Managed by Dexie Cloud
}

export class TimeTrackerDB extends Dexie {
  timeEntries!: Table<TimeEntry, string>;

  constructor() {
    super('TimeTrackerDB', { addons: [dexieCloud] });
    
    // Schema version 1
    this.version(1).stores({
      timeEntries: '@id, date, modifiedAt, isOvertime'
    });

    // Configure cloud connection (stub for MVP, ready for future)
    this.cloud.configure({
      databaseUrl: process.env.NUXT_PUBLIC_DEXIE_CLOUD_URL || '',
      requireAuth: false // disable auth enforcement for MVP local-only mode
    });
  }
}

export const db = new TimeTrackerDB();
