import { db } from './db'

const MIGRATION_KEY = 'dexie_migration_completed'

export const migrateStorage = async () => {
  if (typeof window === 'undefined') return
  
  // Check if already migrated
  if (localStorage.getItem(MIGRATION_KEY)) {
    console.log('[Migration] Database already migrated')
    return
  }

  console.log('[Migration] Starting migration from localStorage to IndexedDB...')

  try {
    const rawData = localStorage.getItem('timeEntries')
    if (!rawData) {
      console.log('[Migration] No localStorage data found. Skipping.')
      localStorage.setItem(MIGRATION_KEY, 'true')
      return
    }

    const parsed = JSON.parse(rawData)
    const entries = parsed.entries || []

    if (entries.length === 0) {
      console.log('[Migration] LocalStorage data is empty. Skipping.')
      localStorage.setItem(MIGRATION_KEY, 'true')
      return
    }

    console.log(`[Migration] Found ${entries.length} entries to migrate`)

    // Transform and insert entries
    await db.transaction('rw', db.timeEntries, async () => {
      for (const entry of entries) {
        // Map old structure to new TimeEntry interface if needed
        // Assuming the store was using a compatible structure, but let's be safe
        await db.timeEntries.add({
          date: entry.date,
          startTime: entry.startTime,
          endTime: entry.endTime || entry.startTime, // Fallback if missing
          tasks: entry.tasks || '',
          isOvertime: entry.isOvertime || entry.isWeekend || false,
          autoGenerated: entry.autoGenerated || false,
          modifiedAt: entry.modifiedAt || Date.now()
          // id is auto-generated by Dexie (@id)
        })
      }
    })

    console.log('[Migration] Migration successful!')
    
    // Mark as completed
    localStorage.setItem(MIGRATION_KEY, 'true')
    
    // Optional: Rename old key to backup instead of deleting
    const backupKey = `timeEntries_backup_${Date.now()}`
    localStorage.setItem(backupKey, rawData)
    localStorage.removeItem('timeEntries')
    console.log(`[Migration] Old data backed up to ${backupKey}`)

  } catch (err) {
    console.error('[Migration] Failed to migrate data:', err)
    // Do NOT set migration key so it retries next time
    // Do NOT delete localStorage data
  }
}
