<template>
  <div class="card bg-base-100 shadow-xl">
    <div class="card-body">
      <h2 class="card-title">{{ isEditing ? 'Edit Entry' : 'New Entry' }}</h2>
      <form @submit.prevent="saveEntry">
        <!-- Date Picker -->
        <div class="form-control w-full">
          <label class="label">
            <span class="label-text">Date</span>
          </label>
          <input type="date" v-model="form.date" class="input input-bordered w-full" required />
        </div>

        <!-- Hours Worked -->
        <div class="form-control w-full">
          <label class="label">
            <span class="label-text">Hours Worked</span>
          </label>
          <input type="number" v-model.number="form.hoursWorked" step="0.5" min="0" max="24" class="input input-bordered w-full" required />
        </div>

        <!-- Tasks -->
        <div class="form-control w-full">
          <label class="label">
            <span class="label-text">Tasks / Notes</span>
          </label>
          <textarea v-model="form.tasks" class="textarea textarea-bordered h-24" placeholder="What did you work on today?"></textarea>
        </div>

        <!-- Actions -->
        <div class="card-actions justify-end mt-4">
          <button type="button" class="btn btn-ghost" @click="$emit('cancel')" v-if="isEditing">Cancel</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, computed } from 'vue';
import type { LegacyTimeEntry } from '@/utils/db';

const props = defineProps<{
  initialData?: LegacyTimeEntry | null;
}>();

const emit = defineEmits(['save', 'cancel']);

const isEditing = computed(() => !!props.initialData);

const form = ref<Partial<LegacyTimeEntry>>({
  date: new Date().toISOString().split('T')[0],
  hoursWorked: 8,
  tasks: '',
  isWeekend: false,
  autoGenerated: false,
});

watch(() => props.initialData, (newData) => {
  if (newData) {
    form.value = { ...newData };
  } else {
    // Reset form
    form.value = {
      date: new Date().toISOString().split('T')[0],
      hoursWorked: 8,
      tasks: '',
      isWeekend: false,
      autoGenerated: false,
    };
  }
}, { immediate: true });

const saveEntry = () => {
  emit('save', { ...form.value, modifiedAt: Date.now() });
};
</script>
